pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: automatic merge for everyone
    conditions:
      - base=main
    actions:
      merge:
        method: merge
        pull_request_rules:
  - name: "Block restricted words in title"
    conditions:
      - title~=DANGER
    actions:
      comment:
        message: "STOP! You used a forbidden word."
      post_check:
        title: "Security Violation"
        summary: "The word DANGER is not allowed."
        success: false 
